costcentername=CC000000
costcenterpage=https://example.com/costcenter
disablecr=false
groupname=Generic Group Name
grouppage=https://example.com/group
region=XX
showlink=false
userdefinedday=other
userdefinedoverrules=true
userfilecontact=Contact Person (ABCD)
