"""Add partial unique index to work locations

Revision ID: 150db98cc607
Revises: 1bfdb920e250
Create Date: 2026-02-28 14:02:06.470136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '150db98cc607'
down_revision: Union[str, Sequence[str], None] = '1bfdb920e250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_locations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_work_location_user_date'), type_='unique')
        batch_op.create_index('ix_unique_active_work_location_user_date', ['user_id', 'date'], unique=True, sqlite_where=sa.text('deleted_at IS NULL'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_locations', schema=None) as batch_op:
        batch_op.drop_index('ix_unique_active_work_location_user_date', sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.create_unique_constraint(batch_op.f('uq_work_location_user_date'), ['user_id', 'date'])

    # ### end Alembic commands ###
