"""Add partial unique index to labels

Revision ID: 1bfdb920e250
Revises: 250499ad49ef
Create Date: 2026-02-28 13:54:56.371737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1bfdb920e250'
down_revision: Union[str, Sequence[str], None] = '250499ad49ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_tracking_labels', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_label_user_name'), type_='unique')
        batch_op.create_index('ix_unique_active_label_user_name', ['user_id', 'name'], unique=True, sqlite_where=sa.text('deleted_at IS NULL'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_tracking_labels', schema=None) as batch_op:
        batch_op.drop_index('ix_unique_active_label_user_name', sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.create_unique_constraint(batch_op.f('uq_label_user_name'), ['user_id', 'name'])

    # ### end Alembic commands ###
