"""initial schema

Revision ID: 250499ad49ef
Revises: 
Create Date: 2026-02-28 13:36:17.851974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '250499ad49ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('time_tracking_labels',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_label_user_name')
    )
    with op.batch_alter_table('time_tracking_labels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_tracking_labels_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_tracking_labels_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_tracking_labels_user_id'), ['user_id'], unique=False)

    op.create_table('work_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_work_location_user_date')
    )
    with op.batch_alter_table('work_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_locations_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_locations_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_locations_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_locations_user_id'), ['user_id'], unique=False)

    op.create_table('time_tracking_tasks',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('stop_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('includes_break', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['time_tracking_labels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('time_tracking_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_tracking_tasks_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_tracking_tasks_label_id'), ['label_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_tracking_tasks_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_tracking_tasks_user_id'), ['user_id'], unique=False)

    op.create_table('time_tracking_templates',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('stop_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['time_tracking_labels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('time_tracking_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_tracking_templates_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_tracking_templates_label_id'), ['label_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_tracking_templates_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_tracking_templates_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_tracking_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_tracking_templates_user_id'))
        batch_op.drop_index(batch_op.f('ix_time_tracking_templates_updated_at'))
        batch_op.drop_index(batch_op.f('ix_time_tracking_templates_label_id'))
        batch_op.drop_index(batch_op.f('ix_time_tracking_templates_deleted_at'))

    op.drop_table('time_tracking_templates')
    with op.batch_alter_table('time_tracking_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_tracking_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_time_tracking_tasks_updated_at'))
        batch_op.drop_index(batch_op.f('ix_time_tracking_tasks_label_id'))
        batch_op.drop_index(batch_op.f('ix_time_tracking_tasks_deleted_at'))

    op.drop_table('time_tracking_tasks')
    with op.batch_alter_table('work_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_locations_user_id'))
        batch_op.drop_index(batch_op.f('ix_work_locations_updated_at'))
        batch_op.drop_index(batch_op.f('ix_work_locations_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_work_locations_date'))

    op.drop_table('work_locations')
    with op.batch_alter_table('time_tracking_labels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_tracking_labels_user_id'))
        batch_op.drop_index(batch_op.f('ix_time_tracking_labels_updated_at'))
        batch_op.drop_index(batch_op.f('ix_time_tracking_labels_deleted_at'))

    op.drop_table('time_tracking_labels')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    # ### end Alembic commands ###
