"""add gantt tasks

Revision ID: b78b041d18dd
Revises: 150db98cc607
Create Date: 2026-02-28 14:10:13.318722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b78b041d18dd'
down_revision: Union[str, Sequence[str], None] = '150db98cc607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gantt_tasks',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('dependencies', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gantt_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gantt_tasks_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_gantt_tasks_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_gantt_tasks_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gantt_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gantt_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_gantt_tasks_updated_at'))
        batch_op.drop_index(batch_op.f('ix_gantt_tasks_deleted_at'))

    op.drop_table('gantt_tasks')
    # ### end Alembic commands ###
